version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                command:
                    yarn
            - run:
                command:
                    yarn test